### ISSUE TITLE
function pointer for delegate

### ISSUE THREAD

**Issue by nblog** [bitwizeshift/Delegate#1]
can I get "void*" from "cpp:: delegate"?

like: [Marshal::GetFunctionPointerForDelegate](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate)

hope for help. 🍺

**Comment by bitwizeshift** [comment]
Hi @nblog, 

`cpp::delegate` objects are _not_ convertible to either a `void*` or just normal function pointer, for two reasons:

1. `cpp::delegate` objects perform small-storage optimizations, and are thus slightly larger than a normal pointer. They are the rough size of two instead of one, and so they can't really collapse into a single pointer.

2. The type erasure performed in `cpp::delegate` erases the original pointer previously bound as an `R(*)(Args...)` type into a more crypting `R(*)(const delegate*, Args...)` stub -- which is an implementation-detail. Once it's erased behind this, only the stub function itself knows the original type -- meaning it's not really possible to get the function pointer out. Exposing this stub would also be a leaky abstraction since users could call it incorrectly leading to UB (so it's not really something I think would be a good idea).

-------

What problem in particular are you hoping to solve by converting to a pointer specifically? It's possible there might be a different workaround that we could come up with if there's a specific problem being solved.

**Comment by nblog** [comment]
thanks @bitwizeshift ,

i want to hook it. but I hope the callback function is a member of a class.

[MessageBoxW](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxw)
```
int MessageBoxW(
  [in, optional] HWND    hWnd,
  [in, optional] LPCWSTR lpText,
  [in, optional] LPCWSTR lpCaption,
  [in]           UINT    uType
);
```

```
class mycls
{
    public:
        ~mycls() { };

        mycls() {  };

        int Detour_MessageBoxW(HWND, LPCWSTR, LPCWSTR, LPCWSTR) {
              return original(.., this.mycontent, ..);
        }
    private:
        std::string mycontent = "hello world!";
}
```

if can "cpp::delegate" to "void*",  i can write assemble `jmp cpp::delegate::ptr` in `MessageBoxW`
